### ISSUE TITLE
Tavamängija auastmed.

### ISSUE THREAD

**Issue by MCGX** [MecCreeper/EESTISADAM#1]
Tavamängijal võiks olla võimalus automaatsele **AFK** süsteemile.
Lisaks selline küsimus, et kas serveri arendaja avaldab serveri versioonidest versioone?

**Comment by MecCreeper** [comment]
Tere!
Mängijatel on lisatud AFK automaatne õigus.
Serverist üldiselt versioone ei avalikustata, küll aga avalikustatakse maailmu, kui toimub maailma vahetus.
